## Exercise

E1: Test whether none of the elements of a given array is zero

[[1,0,2,np.nan],[2,5,0,np.inf]]

In [22]:
# your code here
import numpy as np

x=np.array([[1,0,2,np.nan],[2,5,0,np.inf]])
bool_idx=(x==0)
print(bool_idx)

[[False  True False False]
 [False False  True False]]


E2: Test a given array element-wise for finiteness (not infinity or not a Number)

In [23]:
print(np.isfinite(x))
print(x[np.isfinite(x)])

[[ True  True  True False]
 [ True  True  True False]]
[1. 0. 2. 2. 5. 0.]


E3: Create an array of 10 zeros,10 ones, 10 fives

In [21]:
y=np.array([0,1,5])
yy=np.tile(y,(1,10))

print(yy)

array0=np.zeros(10)
array1=np.ones(10)
array2=np.full(10,5)
array3 = np.concatenate((array0, array1,array2))
print(array3)

[[0 1 5 0 1 5 0 1 5 0 1 5 0 1 5 0 1 5 0 1 5 0 1 5 0 1 5 0 1 5]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


E4: Create a 3x4 matrix filled with values from 10 to 21

In [5]:
x=np.random.randint(10,21,(3,4))
x

array([[18, 14, 20, 20],
       [11, 20, 18, 14],
       [13, 19, 14, 19]])

E5: Create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15


In [7]:
x = np.arange(21)
x[(x >= 9) & (x <= 15)] *= -1
print(x)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]
